apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: hello-container
        image: nodas/hello-world-app:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5000
